/* ============================================================
   Maha Academy — English Adventure — KINDERGARTEN: Letter Sounds Adventure
   Sound gates S, A, T, P, M (from the KG PowerPoint game) + Mahir's Treasure Gate.
   KG children are pre-readers: every word has a picture and is spoken aloud.
   Generated by not_published/games_generator/eng/make_kg.py — edit there.
   ============================================================ */

function shuffle(arr){
  const a = arr.slice();
  for(let i=a.length-1;i>0;i--){
    const j = Math.floor(Math.random()*(i+1));
    [a[i],a[j]] = [a[j],a[i]];
  }
  return a;
}

/* ============ GAME 1: SOUND GATE S ============ */
const SGATE_VOCAB = [
  {
    "id": "snake",
    "en": "snake",
    "ar": "ثعبان",
    "emoji": "🐍"
  },
  {
    "id": "sun",
    "en": "sun",
    "ar": "شمس",
    "emoji": "☀️"
  },
  {
    "id": "sock",
    "en": "sock",
    "ar": "جورب",
    "emoji": "🧦"
  },
  {
    "id": "star",
    "en": "star",
    "ar": "نجمة",
    "emoji": "⭐"
  }
];

const GAME_SGATE = {
  "id": "sgate",
  "emoji": "🐍",
  "titleEn": "Sound Gate S — Snake",
  "titleAr": "بوابة صوت S",
  "character": "mahir",
  "introEn": "This gate hides the secret sound of S. Listen carefully — every sound is a clue!",
  "introAr": "هذه البوابة تُخفي الصوت السري للحرف S. استمع جيدًا — كل صوت هو دليل!",
  "activities": [
    {
      "id": "vocab",
      "type": "vocab",
      "character": "mahir",
      "tagEn": "S Words",
      "tagAr": "كلمات تبدأ بـ S",
      "instructionsEn": "Tap each picture to hear the word.",
      "instructionsAr": "اضغط على كل صورة لسماع الكلمة.",
      "words": SGATE_VOCAB
    },
    {
      "id": "teach",
      "type": "teach",
      "character": "mahir",
      "tagEn": "The S Sound",
      "tagAr": "صوت الحرف S",
      "instructionsEn": "Discover the secret sound of S!",
      "instructionsAr": "اكتشف الصوت السري للحرف S!",
      "teachBlocks": [
        {
          "pillEn": "S says /s/",
          "pillAr": "الحرف S صوته سْ",
          "descEn": "The letter S makes the sound /s/ — like a snake: sss!",
          "descAr": "الحرف S يصدر الصوت سْ — مثل صوت الثعبان: سسس!",
          "examples": [
            {
              "emoji": "🐍",
              "textEn": "<b>s</b>nake <span class=\"ar-text\" style=\"display:block;font-size:14px;\">ثعبان</span>"
            },
            {
              "emoji": "☀️",
              "textEn": "<b>s</b>un <span class=\"ar-text\" style=\"display:block;font-size:14px;\">شمس</span>"
            },
            {
              "emoji": "🧦",
              "textEn": "<b>s</b>ock <span class=\"ar-text\" style=\"display:block;font-size:14px;\">جورب</span>"
            }
          ]
        },
        {
          "pillEn": "Name or sound?",
          "pillAr": "اسم الحرف أم صوته؟",
          "descEn": "The letter's name is \"S\", but its sound is /s/. We use the SOUND to read words!",
          "descAr": "اسم الحرف هو \"S\"، لكن صوته سْ. نستخدم الصوت لنقرأ الكلمات!",
          "examples": [
            {
              "emoji": "🔊",
              "textEn": "/s/ … /s/ … snake! <span class=\"ar-text\" style=\"display:block;font-size:14px;\">سْ … سْ … ثعبان!</span>"
            }
          ]
        }
      ]
    },
    {
      "id": "listen",
      "type": "mcq",
      "character": "maya",
      "audio": true,
      "tagEn": "Listen and Choose",
      "tagAr": "استمع واختر",
      "instructionsEn": "Listen and pick the picture.",
      "instructionsAr": "استمع واختر الصورة.",
      "rounds": [
        {
          "promptEn": "Listen! Which picture did you hear?",
          "promptAr": "استمع! أي صورة سمعتها؟",
          "speak": "sock",
          "options": [
            "🧦 sock",
            "⭐ star",
            "☀️ sun"
          ],
          "correct": "🧦 sock"
        },
        {
          "promptEn": "Listen! Which picture did you hear?",
          "promptAr": "استمع! أي صورة سمعتها؟",
          "speak": "snake",
          "options": [
            "🐍 snake",
            "🧦 sock",
            "☀️ sun"
          ],
          "correct": "🐍 snake"
        },
        {
          "promptEn": "Listen! Which picture did you hear?",
          "promptAr": "استمع! أي صورة سمعتها؟",
          "speak": "sun",
          "options": [
            "🧦 sock",
            "☀️ sun",
            "⭐ star"
          ],
          "correct": "☀️ sun"
        },
        {
          "promptEn": "Listen! Which picture did you hear?",
          "promptAr": "استمع! أي صورة سمعتها؟",
          "speak": "star",
          "options": [
            "☀️ sun",
            "🧦 sock",
            "⭐ star"
          ],
          "correct": "⭐ star"
        }
      ]
    },
    {
      "id": "firstletter",
      "type": "mcq",
      "character": "maya",
      "audio": true,
      "tagEn": "First Letter",
      "tagAr": "الحرف الأول",
      "instructionsEn": "Which letter does the word start with?",
      "instructionsAr": "بأي حرف تبدأ الكلمة؟",
      "rounds": [
        {
          "promptEn": "<span style=\"font-size:44px\">🐍</span><br>Which letter does it start with?",
          "promptAr": "ثعبان — بأي حرف تبدأ الكلمة؟",
          "speak": "snake",
          "options": [
            "A",
            "S",
            "T"
          ],
          "correct": "S"
        },
        {
          "promptEn": "<span style=\"font-size:44px\">☀️</span><br>Which letter does it start with?",
          "promptAr": "شمس — بأي حرف تبدأ الكلمة؟",
          "speak": "sun",
          "options": [
            "S",
            "T",
            "P"
          ],
          "correct": "S"
        },
        {
          "promptEn": "<span style=\"font-size:44px\">🧦</span><br>Which letter does it start with?",
          "promptAr": "جورب — بأي حرف تبدأ الكلمة؟",
          "speak": "sock",
          "options": [
            "P",
            "S",
            "M"
          ],
          "correct": "S"
        },
        {
          "promptEn": "<span style=\"font-size:44px\">⭐</span><br>Which letter does it start with?",
          "promptAr": "نجمة — بأي حرف تبدأ الكلمة؟",
          "speak": "star",
          "options": [
            "A",
            "P",
            "S"
          ],
          "correct": "S"
        }
      ]
    },
    {
      "id": "match",
      "type": "match",
      "character": "marya",
      "tagEn": "Match the Pictures",
      "tagAr": "طابق الصور",
      "instructionsEn": "Match each word to its picture.",
      "instructionsAr": "طابق كل كلمة مع صورتها.",
      "rounds": [
        {
          "pairs": [
            {
              "id": "snake",
              "labelEn": "snake",
              "labelAr": "ثعبان",
              "emoji": "🐍"
            },
            {
              "id": "sun",
              "labelEn": "sun",
              "labelAr": "شمس",
              "emoji": "☀️"
            },
            {
              "id": "sock",
              "labelEn": "sock",
              "labelAr": "جورب",
              "emoji": "🧦"
            },
            {
              "id": "star",
              "labelEn": "star",
              "labelAr": "نجمة",
              "emoji": "⭐"
            }
          ]
        }
      ]
    },
    {
      "id": "challenge",
      "type": "mcq",
      "character": "malik",
      "audio": true,
      "tagEn": "Sound Gate S Challenge",
      "tagAr": "تحدي بوابة S",
      "instructionsEn": "Find the picture that starts with /s/.",
      "instructionsAr": "ابحث عن الصورة التي تبدأ بصوت سْ.",
      "rounds": [
        {
          "promptEn": "Which one starts with the /s/ sound — S?",
          "promptAr": "أي صورة تبدأ بصوت S (سْ)؟",
          "speak": "S. snake",
          "options": [
            "🍅 tomato",
            "🐼 panda",
            "🐍 snake"
          ],
          "correct": "🐍 snake"
        },
        {
          "promptEn": "Which one starts with the /s/ sound — S?",
          "promptAr": "أي صورة تبدأ بصوت S (سْ)؟",
          "speak": "S. sun",
          "options": [
            "☀️ sun",
            "🍎 apple",
            "🗺️ map"
          ],
          "correct": "☀️ sun"
        },
        {
          "promptEn": "Which one starts with the /s/ sound — S?",
          "promptAr": "أي صورة تبدأ بصوت S (سْ)؟",
          "speak": "S. sock",
          "options": [
            "🍅 tomato",
            "🧦 sock",
            "🖊️ pen"
          ],
          "correct": "🧦 sock"
        },
        {
          "promptEn": "Which one starts with the /s/ sound — S?",
          "promptAr": "أي صورة تبدأ بصوت S (سْ)؟",
          "speak": "S. star",
          "options": [
            "⭐ star",
            "🌙 moon",
            "🐒 monkey"
          ],
          "correct": "⭐ star"
        }
      ]
    }
  ]
};

/* ============ GAME 2: SOUND GATE A ============ */
const AGATE_VOCAB = [
  {
    "id": "apple",
    "en": "apple",
    "ar": "تفاحة",
    "emoji": "🍎"
  },
  {
    "id": "ant",
    "en": "ant",
    "ar": "نملة",
    "emoji": "🐜"
  },
  {
    "id": "alligator",
    "en": "alligator",
    "ar": "تمساح",
    "emoji": "🐊"
  },
  {
    "id": "astronaut",
    "en": "astronaut",
    "ar": "رائد فضاء",
    "emoji": "👩‍🚀"
  }
];

const GAME_AGATE = {
  "id": "agate",
  "emoji": "🍎",
  "titleEn": "Sound Gate A — Apple",
  "titleAr": "بوابة صوت A",
  "character": "marya",
  "introEn": "This gate hides the secret sound of A. Listen carefully — every sound is a clue!",
  "introAr": "هذه البوابة تُخفي الصوت السري للحرف A. استمع جيدًا — كل صوت هو دليل!",
  "activities": [
    {
      "id": "vocab",
      "type": "vocab",
      "character": "marya",
      "tagEn": "A Words",
      "tagAr": "كلمات تبدأ بـ A",
      "instructionsEn": "Tap each picture to hear the word.",
      "instructionsAr": "اضغط على كل صورة لسماع الكلمة.",
      "words": AGATE_VOCAB
    },
    {
      "id": "teach",
      "type": "teach",
      "character": "marya",
      "tagEn": "The A Sound",
      "tagAr": "صوت الحرف A",
      "instructionsEn": "Discover the secret sound of A!",
      "instructionsAr": "اكتشف الصوت السري للحرف A!",
      "teachBlocks": [
        {
          "pillEn": "A says /a/",
          "pillAr": "الحرف A صوته أَ",
          "descEn": "The letter A makes the sound /a/ — like in apple: a, a, apple!",
          "descAr": "الحرف A يصدر الصوت أَ — مثل أول صوت في apple: أَ، أَ!",
          "examples": [
            {
              "emoji": "🍎",
              "textEn": "<b>a</b>pple <span class=\"ar-text\" style=\"display:block;font-size:14px;\">تفاحة</span>"
            },
            {
              "emoji": "🐜",
              "textEn": "<b>a</b>nt <span class=\"ar-text\" style=\"display:block;font-size:14px;\">نملة</span>"
            },
            {
              "emoji": "🐊",
              "textEn": "<b>a</b>lligator <span class=\"ar-text\" style=\"display:block;font-size:14px;\">تمساح</span>"
            }
          ]
        },
        {
          "pillEn": "Name or sound?",
          "pillAr": "اسم الحرف أم صوته؟",
          "descEn": "The letter's name is \"A\", but its sound is /a/. We use the SOUND to read words!",
          "descAr": "اسم الحرف هو \"A\"، لكن صوته أَ. نستخدم الصوت لنقرأ الكلمات!",
          "examples": [
            {
              "emoji": "🔊",
              "textEn": "/a/ … /a/ … apple! <span class=\"ar-text\" style=\"display:block;font-size:14px;\">أَ … أَ … تفاحة!</span>"
            }
          ]
        }
      ]
    },
    {
      "id": "listen",
      "type": "mcq",
      "character": "maya",
      "audio": true,
      "tagEn": "Listen and Choose",
      "tagAr": "استمع واختر",
      "instructionsEn": "Listen and pick the picture.",
      "instructionsAr": "استمع واختر الصورة.",
      "rounds": [
        {
          "promptEn": "Listen! Which picture did you hear?",
          "promptAr": "استمع! أي صورة سمعتها؟",
          "speak": "astronaut",
          "options": [
            "👩‍🚀 astronaut",
            "🍎 apple",
            "🐊 alligator"
          ],
          "correct": "👩‍🚀 astronaut"
        },
        {
          "promptEn": "Listen! Which picture did you hear?",
          "promptAr": "استمع! أي صورة سمعتها؟",
          "speak": "ant",
          "options": [
            "🐜 ant",
            "👩‍🚀 astronaut",
            "🐊 alligator"
          ],
          "correct": "🐜 ant"
        },
        {
          "promptEn": "Listen! Which picture did you hear?",
          "promptAr": "استمع! أي صورة سمعتها؟",
          "speak": "apple",
          "options": [
            "🍎 apple",
            "👩‍🚀 astronaut",
            "🐊 alligator"
          ],
          "correct": "🍎 apple"
        },
        {
          "promptEn": "Listen! Which picture did you hear?",
          "promptAr": "استمع! أي صورة سمعتها؟",
          "speak": "alligator",
          "options": [
            "🐊 alligator",
            "🐜 ant",
            "👩‍🚀 astronaut"
          ],
          "correct": "🐊 alligator"
        }
      ]
    },
    {
      "id": "firstletter",
      "type": "mcq",
      "character": "maya",
      "audio": true,
      "tagEn": "First Letter",
      "tagAr": "الحرف الأول",
      "instructionsEn": "Which letter does the word start with?",
      "instructionsAr": "بأي حرف تبدأ الكلمة؟",
      "rounds": [
        {
          "promptEn": "<span style=\"font-size:44px\">🍎</span><br>Which letter does it start with?",
          "promptAr": "تفاحة — بأي حرف تبدأ الكلمة؟",
          "speak": "apple",
          "options": [
            "A",
            "S",
            "T"
          ],
          "correct": "A"
        },
        {
          "promptEn": "<span style=\"font-size:44px\">🐜</span><br>Which letter does it start with?",
          "promptAr": "نملة — بأي حرف تبدأ الكلمة؟",
          "speak": "ant",
          "options": [
            "A",
            "P",
            "M"
          ],
          "correct": "A"
        },
        {
          "promptEn": "<span style=\"font-size:44px\">🐊</span><br>Which letter does it start with?",
          "promptAr": "تمساح — بأي حرف تبدأ الكلمة؟",
          "speak": "alligator",
          "options": [
            "M",
            "A",
            "P"
          ],
          "correct": "A"
        },
        {
          "promptEn": "<span style=\"font-size:44px\">👩‍🚀</span><br>Which letter does it start with?",
          "promptAr": "رائد فضاء — بأي حرف تبدأ الكلمة؟",
          "speak": "astronaut",
          "options": [
            "T",
            "S",
            "A"
          ],
          "correct": "A"
        }
      ]
    },
    {
      "id": "match",
      "type": "match",
      "character": "marya",
      "tagEn": "Match the Pictures",
      "tagAr": "طابق الصور",
      "instructionsEn": "Match each word to its picture.",
      "instructionsAr": "طابق كل كلمة مع صورتها.",
      "rounds": [
        {
          "pairs": [
            {
              "id": "apple",
              "labelEn": "apple",
              "labelAr": "تفاحة",
              "emoji": "🍎"
            },
            {
              "id": "ant",
              "labelEn": "ant",
              "labelAr": "نملة",
              "emoji": "🐜"
            },
            {
              "id": "alligator",
              "labelEn": "alligator",
              "labelAr": "تمساح",
              "emoji": "🐊"
            },
            {
              "id": "astronaut",
              "labelEn": "astronaut",
              "labelAr": "رائد فضاء",
              "emoji": "👩‍🚀"
            }
          ]
        }
      ]
    },
    {
      "id": "challenge",
      "type": "mcq",
      "character": "malik",
      "audio": true,
      "tagEn": "Sound Gate A Challenge",
      "tagAr": "تحدي بوابة A",
      "instructionsEn": "Find the picture that starts with /a/.",
      "instructionsAr": "ابحث عن الصورة التي تبدأ بصوت أَ.",
      "rounds": [
        {
          "promptEn": "Which one starts with the /a/ sound — A?",
          "promptAr": "أي صورة تبدأ بصوت A (أَ)؟",
          "speak": "A. apple",
          "options": [
            "🐯 tiger",
            "🍎 apple",
            "🚰 tap"
          ],
          "correct": "🍎 apple"
        },
        {
          "promptEn": "Which one starts with the /a/ sound — A?",
          "promptAr": "أي صورة تبدأ بصوت A (أَ)؟",
          "speak": "A. ant",
          "options": [
            "🐜 ant",
            "☀️ sun",
            "🧦 sock"
          ],
          "correct": "🐜 ant"
        },
        {
          "promptEn": "Which one starts with the /a/ sound — A?",
          "promptAr": "أي صورة تبدأ بصوت A (أَ)؟",
          "speak": "A. alligator",
          "options": [
            "🐢 turtle",
            "🥛 milk",
            "🐊 alligator"
          ],
          "correct": "🐊 alligator"
        },
        {
          "promptEn": "Which one starts with the /a/ sound — A?",
          "promptAr": "أي صورة تبدأ بصوت A (أَ)؟",
          "speak": "A. astronaut",
          "options": [
            "👩‍🚀 astronaut",
            "🥛 milk",
            "🍅 tomato"
          ],
          "correct": "👩‍🚀 astronaut"
        }
      ]
    }
  ]
};

/* ============ GAME 3: SOUND GATE T ============ */
const TGATE_VOCAB = [
  {
    "id": "tiger",
    "en": "tiger",
    "ar": "نمر",
    "emoji": "🐯"
  },
  {
    "id": "turtle",
    "en": "turtle",
    "ar": "سلحفاة",
    "emoji": "🐢"
  },
  {
    "id": "tap",
    "en": "tap",
    "ar": "صنبور",
    "emoji": "🚰"
  },
  {
    "id": "tomato",
    "en": "tomato",
    "ar": "طماطم",
    "emoji": "🍅"
  }
];

const GAME_TGATE = {
  "id": "tgate",
  "emoji": "🐯",
  "titleEn": "Sound Gate T — Tiger",
  "titleAr": "بوابة صوت T",
  "character": "mahir",
  "introEn": "This gate hides the secret sound of T. Listen carefully — every sound is a clue!",
  "introAr": "هذه البوابة تُخفي الصوت السري للحرف T. استمع جيدًا — كل صوت هو دليل!",
  "activities": [
    {
      "id": "vocab",
      "type": "vocab",
      "character": "mahir",
      "tagEn": "T Words",
      "tagAr": "كلمات تبدأ بـ T",
      "instructionsEn": "Tap each picture to hear the word.",
      "instructionsAr": "اضغط على كل صورة لسماع الكلمة.",
      "words": TGATE_VOCAB
    },
    {
      "id": "teach",
      "type": "teach",
      "character": "mahir",
      "tagEn": "The T Sound",
      "tagAr": "صوت الحرف T",
      "instructionsEn": "Discover the secret sound of T!",
      "instructionsAr": "اكتشف الصوت السري للحرف T!",
      "teachBlocks": [
        {
          "pillEn": "T says /t/",
          "pillAr": "الحرف T صوته تْ",
          "descEn": "The letter T makes the sound /t/ — like a clock: t, t, t!",
          "descAr": "الحرف T يصدر الصوت تْ — مثل صوت الساعة: تْ، تْ، تْ!",
          "examples": [
            {
              "emoji": "🐯",
              "textEn": "<b>t</b>iger <span class=\"ar-text\" style=\"display:block;font-size:14px;\">نمر</span>"
            },
            {
              "emoji": "🐢",
              "textEn": "<b>t</b>urtle <span class=\"ar-text\" style=\"display:block;font-size:14px;\">سلحفاة</span>"
            },
            {
              "emoji": "🚰",
              "textEn": "<b>t</b>ap <span class=\"ar-text\" style=\"display:block;font-size:14px;\">صنبور</span>"
            }
          ]
        },
        {
          "pillEn": "Name or sound?",
          "pillAr": "اسم الحرف أم صوته؟",
          "descEn": "The letter's name is \"T\", but its sound is /t/. We use the SOUND to read words!",
          "descAr": "اسم الحرف هو \"T\"، لكن صوته تْ. نستخدم الصوت لنقرأ الكلمات!",
          "examples": [
            {
              "emoji": "🔊",
              "textEn": "/t/ … /t/ … tiger! <span class=\"ar-text\" style=\"display:block;font-size:14px;\">تْ … تْ … نمر!</span>"
            }
          ]
        }
      ]
    },
    {
      "id": "listen",
      "type": "mcq",
      "character": "maya",
      "audio": true,
      "tagEn": "Listen and Choose",
      "tagAr": "استمع واختر",
      "instructionsEn": "Listen and pick the picture.",
      "instructionsAr": "استمع واختر الصورة.",
      "rounds": [
        {
          "promptEn": "Listen! Which picture did you hear?",
          "promptAr": "استمع! أي صورة سمعتها؟",
          "speak": "tiger",
          "options": [
            "🐢 turtle",
            "🚰 tap",
            "🐯 tiger"
          ],
          "correct": "🐯 tiger"
        },
        {
          "promptEn": "Listen! Which picture did you hear?",
          "promptAr": "استمع! أي صورة سمعتها؟",
          "speak": "tap",
          "options": [
            "🐯 tiger",
            "🐢 turtle",
            "🚰 tap"
          ],
          "correct": "🚰 tap"
        },
        {
          "promptEn": "Listen! Which picture did you hear?",
          "promptAr": "استمع! أي صورة سمعتها؟",
          "speak": "turtle",
          "options": [
            "🐯 tiger",
            "🐢 turtle",
            "🚰 tap"
          ],
          "correct": "🐢 turtle"
        },
        {
          "promptEn": "Listen! Which picture did you hear?",
          "promptAr": "استمع! أي صورة سمعتها؟",
          "speak": "tomato",
          "options": [
            "🚰 tap",
            "🐯 tiger",
            "🍅 tomato"
          ],
          "correct": "🍅 tomato"
        }
      ]
    },
    {
      "id": "firstletter",
      "type": "mcq",
      "character": "maya",
      "audio": true,
      "tagEn": "First Letter",
      "tagAr": "الحرف الأول",
      "instructionsEn": "Which letter does the word start with?",
      "instructionsAr": "بأي حرف تبدأ الكلمة؟",
      "rounds": [
        {
          "promptEn": "<span style=\"font-size:44px\">🐯</span><br>Which letter does it start with?",
          "promptAr": "نمر — بأي حرف تبدأ الكلمة؟",
          "speak": "tiger",
          "options": [
            "M",
            "T",
            "P"
          ],
          "correct": "T"
        },
        {
          "promptEn": "<span style=\"font-size:44px\">🐢</span><br>Which letter does it start with?",
          "promptAr": "سلحفاة — بأي حرف تبدأ الكلمة؟",
          "speak": "turtle",
          "options": [
            "A",
            "T",
            "P"
          ],
          "correct": "T"
        },
        {
          "promptEn": "<span style=\"font-size:44px\">🚰</span><br>Which letter does it start with?",
          "promptAr": "صنبور — بأي حرف تبدأ الكلمة؟",
          "speak": "tap",
          "options": [
            "T",
            "M",
            "P"
          ],
          "correct": "T"
        },
        {
          "promptEn": "<span style=\"font-size:44px\">🍅</span><br>Which letter does it start with?",
          "promptAr": "طماطم — بأي حرف تبدأ الكلمة؟",
          "speak": "tomato",
          "options": [
            "T",
            "S",
            "M"
          ],
          "correct": "T"
        }
      ]
    },
    {
      "id": "match",
      "type": "match",
      "character": "marya",
      "tagEn": "Match the Pictures",
      "tagAr": "طابق الصور",
      "instructionsEn": "Match each word to its picture.",
      "instructionsAr": "طابق كل كلمة مع صورتها.",
      "rounds": [
        {
          "pairs": [
            {
              "id": "tiger",
              "labelEn": "tiger",
              "labelAr": "نمر",
              "emoji": "🐯"
            },
            {
              "id": "turtle",
              "labelEn": "turtle",
              "labelAr": "سلحفاة",
              "emoji": "🐢"
            },
            {
              "id": "tap",
              "labelEn": "tap",
              "labelAr": "صنبور",
              "emoji": "🚰"
            },
            {
              "id": "tomato",
              "labelEn": "tomato",
              "labelAr": "طماطم",
              "emoji": "🍅"
            }
          ]
        }
      ]
    },
    {
      "id": "challenge",
      "type": "mcq",
      "character": "malik",
      "audio": true,
      "tagEn": "Sound Gate T Challenge",
      "tagAr": "تحدي بوابة T",
      "instructionsEn": "Find the picture that starts with /t/.",
      "instructionsAr": "ابحث عن الصورة التي تبدأ بصوت تْ.",
      "rounds": [
        {
          "promptEn": "Which one starts with the /t/ sound — T?",
          "promptAr": "أي صورة تبدأ بصوت T (تْ)؟",
          "speak": "T. tiger",
          "options": [
            "🐯 tiger",
            "☀️ sun",
            "🌙 moon"
          ],
          "correct": "🐯 tiger"
        },
        {
          "promptEn": "Which one starts with the /t/ sound — T?",
          "promptAr": "أي صورة تبدأ بصوت T (تْ)؟",
          "speak": "T. turtle",
          "options": [
            "🧦 sock",
            "🖊️ pen",
            "🐢 turtle"
          ],
          "correct": "🐢 turtle"
        },
        {
          "promptEn": "Which one starts with the /t/ sound — T?",
          "promptAr": "أي صورة تبدأ بصوت T (تْ)؟",
          "speak": "T. tap",
          "options": [
            "🥛 milk",
            "🚰 tap",
            "🖊️ pen"
          ],
          "correct": "🚰 tap"
        },
        {
          "promptEn": "Which one starts with the /t/ sound — T?",
          "promptAr": "أي صورة تبدأ بصوت T (تْ)؟",
          "speak": "T. tomato",
          "options": [
            "👩‍🚀 astronaut",
            "🍅 tomato",
            "🥛 milk"
          ],
          "correct": "🍅 tomato"
        }
      ]
    }
  ]
};

/* ============ GAME 4: SOUND GATE P ============ */
const PGATE_VOCAB = [
  {
    "id": "pig",
    "en": "pig",
    "ar": "خنزير صغير",
    "emoji": "🐷"
  },
  {
    "id": "panda",
    "en": "panda",
    "ar": "باندا",
    "emoji": "🐼"
  },
  {
    "id": "pineapple",
    "en": "pineapple",
    "ar": "أناناس",
    "emoji": "🍍"
  },
  {
    "id": "pen",
    "en": "pen",
    "ar": "قلم",
    "emoji": "🖊️"
  }
];

const GAME_PGATE = {
  "id": "pgate",
  "emoji": "🐷",
  "titleEn": "Sound Gate P — Pig",
  "titleAr": "بوابة صوت P",
  "character": "marya",
  "introEn": "This gate hides the secret sound of P. Listen carefully — every sound is a clue!",
  "introAr": "هذه البوابة تُخفي الصوت السري للحرف P. استمع جيدًا — كل صوت هو دليل!",
  "activities": [
    {
      "id": "vocab",
      "type": "vocab",
      "character": "marya",
      "tagEn": "P Words",
      "tagAr": "كلمات تبدأ بـ P",
      "instructionsEn": "Tap each picture to hear the word.",
      "instructionsAr": "اضغط على كل صورة لسماع الكلمة.",
      "words": PGATE_VOCAB
    },
    {
      "id": "teach",
      "type": "teach",
      "character": "marya",
      "tagEn": "The P Sound",
      "tagAr": "صوت الحرف P",
      "instructionsEn": "Discover the secret sound of P!",
      "instructionsAr": "اكتشف الصوت السري للحرف P!",
      "teachBlocks": [
        {
          "pillEn": "P says /p/",
          "pillAr": "الحرف P صوته بْ",
          "descEn": "The letter P makes the sound /p/ — a little puff of air: p, p, p!",
          "descAr": "الحرف P يصدر الصوت بْ — نفخة هواء صغيرة: بْ، بْ، بْ!",
          "examples": [
            {
              "emoji": "🐷",
              "textEn": "<b>p</b>ig <span class=\"ar-text\" style=\"display:block;font-size:14px;\">خنزير صغير</span>"
            },
            {
              "emoji": "🐼",
              "textEn": "<b>p</b>anda <span class=\"ar-text\" style=\"display:block;font-size:14px;\">باندا</span>"
            },
            {
              "emoji": "🍍",
              "textEn": "<b>p</b>ineapple <span class=\"ar-text\" style=\"display:block;font-size:14px;\">أناناس</span>"
            }
          ]
        },
        {
          "pillEn": "Name or sound?",
          "pillAr": "اسم الحرف أم صوته؟",
          "descEn": "The letter's name is \"P\", but its sound is /p/. We use the SOUND to read words!",
          "descAr": "اسم الحرف هو \"P\"، لكن صوته بْ. نستخدم الصوت لنقرأ الكلمات!",
          "examples": [
            {
              "emoji": "🔊",
              "textEn": "/p/ … /p/ … pig! <span class=\"ar-text\" style=\"display:block;font-size:14px;\">بْ … بْ … خنزير صغير!</span>"
            }
          ]
        }
      ]
    },
    {
      "id": "listen",
      "type": "mcq",
      "character": "maya",
      "audio": true,
      "tagEn": "Listen and Choose",
      "tagAr": "استمع واختر",
      "instructionsEn": "Listen and pick the picture.",
      "instructionsAr": "استمع واختر الصورة.",
      "rounds": [
        {
          "promptEn": "Listen! Which picture did you hear?",
          "promptAr": "استمع! أي صورة سمعتها؟",
          "speak": "pig",
          "options": [
            "🐷 pig",
            "🐼 panda",
            "🖊️ pen"
          ],
          "correct": "🐷 pig"
        },
        {
          "promptEn": "Listen! Which picture did you hear?",
          "promptAr": "استمع! أي صورة سمعتها؟",
          "speak": "pen",
          "options": [
            "🖊️ pen",
            "🍍 pineapple",
            "🐼 panda"
          ],
          "correct": "🖊️ pen"
        },
        {
          "promptEn": "Listen! Which picture did you hear?",
          "promptAr": "استمع! أي صورة سمعتها؟",
          "speak": "panda",
          "options": [
            "🍍 pineapple",
            "🐼 panda",
            "🐷 pig"
          ],
          "correct": "🐼 panda"
        },
        {
          "promptEn": "Listen! Which picture did you hear?",
          "promptAr": "استمع! أي صورة سمعتها؟",
          "speak": "pineapple",
          "options": [
            "🍍 pineapple",
            "🖊️ pen",
            "🐷 pig"
          ],
          "correct": "🍍 pineapple"
        }
      ]
    },
    {
      "id": "firstletter",
      "type": "mcq",
      "character": "maya",
      "audio": true,
      "tagEn": "First Letter",
      "tagAr": "الحرف الأول",
      "instructionsEn": "Which letter does the word start with?",
      "instructionsAr": "بأي حرف تبدأ الكلمة؟",
      "rounds": [
        {
          "promptEn": "<span style=\"font-size:44px\">🐷</span><br>Which letter does it start with?",
          "promptAr": "خنزير صغير — بأي حرف تبدأ الكلمة؟",
          "speak": "pig",
          "options": [
            "S",
            "P",
            "T"
          ],
          "correct": "P"
        },
        {
          "promptEn": "<span style=\"font-size:44px\">🐼</span><br>Which letter does it start with?",
          "promptAr": "باندا — بأي حرف تبدأ الكلمة؟",
          "speak": "panda",
          "options": [
            "P",
            "T",
            "A"
          ],
          "correct": "P"
        },
        {
          "promptEn": "<span style=\"font-size:44px\">🍍</span><br>Which letter does it start with?",
          "promptAr": "أناناس — بأي حرف تبدأ الكلمة؟",
          "speak": "pineapple",
          "options": [
            "M",
            "P",
            "S"
          ],
          "correct": "P"
        },
        {
          "promptEn": "<span style=\"font-size:44px\">🖊️</span><br>Which letter does it start with?",
          "promptAr": "قلم — بأي حرف تبدأ الكلمة؟",
          "speak": "pen",
          "options": [
            "S",
            "M",
            "P"
          ],
          "correct": "P"
        }
      ]
    },
    {
      "id": "match",
      "type": "match",
      "character": "marya",
      "tagEn": "Match the Pictures",
      "tagAr": "طابق الصور",
      "instructionsEn": "Match each word to its picture.",
      "instructionsAr": "طابق كل كلمة مع صورتها.",
      "rounds": [
        {
          "pairs": [
            {
              "id": "pig",
              "labelEn": "pig",
              "labelAr": "خنزير صغير",
              "emoji": "🐷"
            },
            {
              "id": "panda",
              "labelEn": "panda",
              "labelAr": "باندا",
              "emoji": "🐼"
            },
            {
              "id": "pineapple",
              "labelEn": "pineapple",
              "labelAr": "أناناس",
              "emoji": "🍍"
            },
            {
              "id": "pen",
              "labelEn": "pen",
              "labelAr": "قلم",
              "emoji": "🖊️"
            }
          ]
        }
      ]
    },
    {
      "id": "challenge",
      "type": "mcq",
      "character": "malik",
      "audio": true,
      "tagEn": "Sound Gate P Challenge",
      "tagAr": "تحدي بوابة P",
      "instructionsEn": "Find the picture that starts with /p/.",
      "instructionsAr": "ابحث عن الصورة التي تبدأ بصوت بْ.",
      "rounds": [
        {
          "promptEn": "Which one starts with the /p/ sound — P?",
          "promptAr": "أي صورة تبدأ بصوت P (بْ)؟",
          "speak": "P. pig",
          "options": [
            "🐒 monkey",
            "🐢 turtle",
            "🐷 pig"
          ],
          "correct": "🐷 pig"
        },
        {
          "promptEn": "Which one starts with the /p/ sound — P?",
          "promptAr": "أي صورة تبدأ بصوت P (بْ)؟",
          "speak": "P. panda",
          "options": [
            "🌙 moon",
            "🐍 snake",
            "🐼 panda"
          ],
          "correct": "🐼 panda"
        },
        {
          "promptEn": "Which one starts with the /p/ sound — P?",
          "promptAr": "أي صورة تبدأ بصوت P (بْ)؟",
          "speak": "P. pineapple",
          "options": [
            "☀️ sun",
            "🍍 pineapple",
            "🚰 tap"
          ],
          "correct": "🍍 pineapple"
        },
        {
          "promptEn": "Which one starts with the /p/ sound — P?",
          "promptAr": "أي صورة تبدأ بصوت P (بْ)؟",
          "speak": "P. pen",
          "options": [
            "🐒 monkey",
            "🖊️ pen",
            "🗺️ map"
          ],
          "correct": "🖊️ pen"
        }
      ]
    }
  ]
};

/* ============ GAME 5: SOUND GATE M ============ */
const MGATE_VOCAB = [
  {
    "id": "moon",
    "en": "moon",
    "ar": "قمر",
    "emoji": "🌙"
  },
  {
    "id": "map",
    "en": "map",
    "ar": "خريطة",
    "emoji": "🗺️"
  },
  {
    "id": "monkey",
    "en": "monkey",
    "ar": "قرد",
    "emoji": "🐒"
  },
  {
    "id": "milk",
    "en": "milk",
    "ar": "حليب",
    "emoji": "🥛"
  }
];

const GAME_MGATE = {
  "id": "mgate",
  "emoji": "🌙",
  "titleEn": "Sound Gate M — Moon",
  "titleAr": "بوابة صوت M",
  "character": "mahir",
  "introEn": "This gate hides the secret sound of M. Listen carefully — every sound is a clue!",
  "introAr": "هذه البوابة تُخفي الصوت السري للحرف M. استمع جيدًا — كل صوت هو دليل!",
  "activities": [
    {
      "id": "vocab",
      "type": "vocab",
      "character": "mahir",
      "tagEn": "M Words",
      "tagAr": "كلمات تبدأ بـ M",
      "instructionsEn": "Tap each picture to hear the word.",
      "instructionsAr": "اضغط على كل صورة لسماع الكلمة.",
      "words": MGATE_VOCAB
    },
    {
      "id": "teach",
      "type": "teach",
      "character": "mahir",
      "tagEn": "The M Sound",
      "tagAr": "صوت الحرف M",
      "instructionsEn": "Discover the secret sound of M!",
      "instructionsAr": "اكتشف الصوت السري للحرف M!",
      "teachBlocks": [
        {
          "pillEn": "M says /m/",
          "pillAr": "الحرف M صوته مْ",
          "descEn": "The letter M makes the sound /m/ — like yummy food: mmm!",
          "descAr": "الحرف M يصدر الصوت مْ — مثل الطعام اللذيذ: مممم!",
          "examples": [
            {
              "emoji": "🌙",
              "textEn": "<b>m</b>oon <span class=\"ar-text\" style=\"display:block;font-size:14px;\">قمر</span>"
            },
            {
              "emoji": "🗺️",
              "textEn": "<b>m</b>ap <span class=\"ar-text\" style=\"display:block;font-size:14px;\">خريطة</span>"
            },
            {
              "emoji": "🐒",
              "textEn": "<b>m</b>onkey <span class=\"ar-text\" style=\"display:block;font-size:14px;\">قرد</span>"
            }
          ]
        },
        {
          "pillEn": "Name or sound?",
          "pillAr": "اسم الحرف أم صوته؟",
          "descEn": "The letter's name is \"M\", but its sound is /m/. We use the SOUND to read words!",
          "descAr": "اسم الحرف هو \"M\"، لكن صوته مْ. نستخدم الصوت لنقرأ الكلمات!",
          "examples": [
            {
              "emoji": "🔊",
              "textEn": "/m/ … /m/ … moon! <span class=\"ar-text\" style=\"display:block;font-size:14px;\">مْ … مْ … قمر!</span>"
            }
          ]
        }
      ]
    },
    {
      "id": "listen",
      "type": "mcq",
      "character": "maya",
      "audio": true,
      "tagEn": "Listen and Choose",
      "tagAr": "استمع واختر",
      "instructionsEn": "Listen and pick the picture.",
      "instructionsAr": "استمع واختر الصورة.",
      "rounds": [
        {
          "promptEn": "Listen! Which picture did you hear?",
          "promptAr": "استمع! أي صورة سمعتها؟",
          "speak": "moon",
          "options": [
            "🌙 moon",
            "🗺️ map",
            "🐒 monkey"
          ],
          "correct": "🌙 moon"
        },
        {
          "promptEn": "Listen! Which picture did you hear?",
          "promptAr": "استمع! أي صورة سمعتها؟",
          "speak": "map",
          "options": [
            "🗺️ map",
            "🥛 milk",
            "🐒 monkey"
          ],
          "correct": "🗺️ map"
        },
        {
          "promptEn": "Listen! Which picture did you hear?",
          "promptAr": "استمع! أي صورة سمعتها؟",
          "speak": "monkey",
          "options": [
            "🐒 monkey",
            "🌙 moon",
            "🗺️ map"
          ],
          "correct": "🐒 monkey"
        },
        {
          "promptEn": "Listen! Which picture did you hear?",
          "promptAr": "استمع! أي صورة سمعتها؟",
          "speak": "milk",
          "options": [
            "🥛 milk",
            "🗺️ map",
            "🌙 moon"
          ],
          "correct": "🥛 milk"
        }
      ]
    },
    {
      "id": "firstletter",
      "type": "mcq",
      "character": "maya",
      "audio": true,
      "tagEn": "First Letter",
      "tagAr": "الحرف الأول",
      "instructionsEn": "Which letter does the word start with?",
      "instructionsAr": "بأي حرف تبدأ الكلمة؟",
      "rounds": [
        {
          "promptEn": "<span style=\"font-size:44px\">🌙</span><br>Which letter does it start with?",
          "promptAr": "قمر — بأي حرف تبدأ الكلمة؟",
          "speak": "moon",
          "options": [
            "P",
            "M",
            "T"
          ],
          "correct": "M"
        },
        {
          "promptEn": "<span style=\"font-size:44px\">🗺️</span><br>Which letter does it start with?",
          "promptAr": "خريطة — بأي حرف تبدأ الكلمة؟",
          "speak": "map",
          "options": [
            "A",
            "M",
            "T"
          ],
          "correct": "M"
        },
        {
          "promptEn": "<span style=\"font-size:44px\">🐒</span><br>Which letter does it start with?",
          "promptAr": "قرد — بأي حرف تبدأ الكلمة؟",
          "speak": "monkey",
          "options": [
            "A",
            "M",
            "S"
          ],
          "correct": "M"
        },
        {
          "promptEn": "<span style=\"font-size:44px\">🥛</span><br>Which letter does it start with?",
          "promptAr": "حليب — بأي حرف تبدأ الكلمة؟",
          "speak": "milk",
          "options": [
            "M",
            "A",
            "P"
          ],
          "correct": "M"
        }
      ]
    },
    {
      "id": "match",
      "type": "match",
      "character": "marya",
      "tagEn": "Match the Pictures",
      "tagAr": "طابق الصور",
      "instructionsEn": "Match each word to its picture.",
      "instructionsAr": "طابق كل كلمة مع صورتها.",
      "rounds": [
        {
          "pairs": [
            {
              "id": "moon",
              "labelEn": "moon",
              "labelAr": "قمر",
              "emoji": "🌙"
            },
            {
              "id": "map",
              "labelEn": "map",
              "labelAr": "خريطة",
              "emoji": "🗺️"
            },
            {
              "id": "monkey",
              "labelEn": "monkey",
              "labelAr": "قرد",
              "emoji": "🐒"
            },
            {
              "id": "milk",
              "labelEn": "milk",
              "labelAr": "حليب",
              "emoji": "🥛"
            }
          ]
        }
      ]
    },
    {
      "id": "challenge",
      "type": "mcq",
      "character": "malik",
      "audio": true,
      "tagEn": "Sound Gate M Challenge",
      "tagAr": "تحدي بوابة M",
      "instructionsEn": "Find the picture that starts with /m/.",
      "instructionsAr": "ابحث عن الصورة التي تبدأ بصوت مْ.",
      "rounds": [
        {
          "promptEn": "Which one starts with the /m/ sound — M?",
          "promptAr": "أي صورة تبدأ بصوت M (مْ)؟",
          "speak": "M. moon",
          "options": [
            "⭐ star",
            "🐼 panda",
            "🌙 moon"
          ],
          "correct": "🌙 moon"
        },
        {
          "promptEn": "Which one starts with the /m/ sound — M?",
          "promptAr": "أي صورة تبدأ بصوت M (مْ)؟",
          "speak": "M. map",
          "options": [
            "🗺️ map",
            "☀️ sun",
            "🐍 snake"
          ],
          "correct": "🗺️ map"
        },
        {
          "promptEn": "Which one starts with the /m/ sound — M?",
          "promptAr": "أي صورة تبدأ بصوت M (مْ)؟",
          "speak": "M. monkey",
          "options": [
            "🐼 panda",
            "🐒 monkey",
            "🐯 tiger"
          ],
          "correct": "🐒 monkey"
        },
        {
          "promptEn": "Which one starts with the /m/ sound — M?",
          "promptAr": "أي صورة تبدأ بصوت M (مْ)؟",
          "speak": "M. milk",
          "options": [
            "🐜 ant",
            "🐍 snake",
            "🥛 milk"
          ],
          "correct": "🥛 milk"
        }
      ]
    }
  ]
};

/* ============ GAME 6: MAHIR'S TREASURE GATE ============ */
const GAME_TREASURE = {
  "id": "treasure",
  "emoji": "💎",
  "titleEn": "Mahir's Treasure Gate",
  "titleAr": "بوابة كنز ماهر",
  "character": "mahir",
  "introEn": "One last challenge, Explorer! Build words and listen for sounds to open the treasure!",
  "introAr": "تحدٍّ أخير يا مستكشف! كوّن الكلمات واستمع للأصوات لتفتح الكنز!",
  "activities": [
    {
      "id": "teach",
      "type": "teach",
      "character": "marya",
      "tagEn": "Marya's Word Workshop",
      "tagAr": "ورشة ماريا للكلمات",
      "instructionsEn": "Sounds join together to make words!",
      "instructionsAr": "الأصوات تتّصل لتصنع كلمات!",
      "teachBlocks": [
        {
          "pillEn": "s … a … t → sat",
          "pillAr": "سْ … أَ … تْ ← sat",
          "descEn": "Say each sound, then blend them together fast: s-a-t, sat!",
          "descAr": "قل كل صوت، ثم اجمعها بسرعة: s-a-t ← sat!",
          "examples": [
            {
              "emoji": "🪑",
              "textEn": "s · a · t → <b>sat</b>"
            },
            {
              "emoji": "🗺️",
              "textEn": "m · a · p → <b>map</b>"
            },
            {
              "emoji": "🚰",
              "textEn": "t · a · p → <b>tap</b>"
            }
          ]
        }
      ]
    },
    {
      "id": "build",
      "type": "order",
      "character": "marya",
      "speakOnPlace": true,
      "tagEn": "Build the Word",
      "tagAr": "كوّن الكلمة",
      "instructionsEn": "Tap the letters in order to build the word.",
      "instructionsAr": "اضغط على الحروف بالترتيب لتكوّن الكلمة.",
      "rounds": [
        {
          "storyEn": "🪑 sat",
          "storyAr": "جلسَ",
          "storyBig": true,
          "items": [
            {
              "id": "sat0",
              "labelEn": "S"
            },
            {
              "id": "sat1",
              "labelEn": "A"
            },
            {
              "id": "sat2",
              "labelEn": "T"
            }
          ]
        },
        {
          "storyEn": "🤚 pat",
          "storyAr": "ربّتَ",
          "storyBig": true,
          "items": [
            {
              "id": "pat0",
              "labelEn": "P"
            },
            {
              "id": "pat1",
              "labelEn": "A"
            },
            {
              "id": "pat2",
              "labelEn": "T"
            }
          ]
        },
        {
          "storyEn": "🟫 mat",
          "storyAr": "سجّادة",
          "storyBig": true,
          "items": [
            {
              "id": "mat0",
              "labelEn": "M"
            },
            {
              "id": "mat1",
              "labelEn": "A"
            },
            {
              "id": "mat2",
              "labelEn": "T"
            }
          ]
        },
        {
          "storyEn": "🚰 tap",
          "storyAr": "صنبور",
          "storyBig": true,
          "items": [
            {
              "id": "tap0",
              "labelEn": "T"
            },
            {
              "id": "tap1",
              "labelEn": "A"
            },
            {
              "id": "tap2",
              "labelEn": "P"
            }
          ]
        },
        {
          "storyEn": "🗺️ map",
          "storyAr": "خريطة",
          "storyBig": true,
          "items": [
            {
              "id": "map0",
              "labelEn": "M"
            },
            {
              "id": "map1",
              "labelEn": "A"
            },
            {
              "id": "map2",
              "labelEn": "P"
            }
          ]
        }
      ]
    },
    {
      "id": "samediff",
      "type": "mcq",
      "character": "mahir",
      "audio": true,
      "tagEn": "Same or Different?",
      "tagAr": "نفس الصوت أم مختلف؟",
      "instructionsEn": "Listen to the first sound of each word.",
      "instructionsAr": "استمع إلى أول صوت في كل كلمة.",
      "rounds": [
        {
          "promptEn": "☀️ sun — 🧦 sock: same first sound, or different?",
          "promptAr": "هل تبدأ الكلمتان بنفس الصوت أم بصوت مختلف؟",
          "speak": "sun … sock",
          "options": [
            "✅ same",
            "❌ different"
          ],
          "correct": "✅ same"
        },
        {
          "promptEn": "☀️ sun — 🌙 moon: same first sound, or different?",
          "promptAr": "هل تبدأ الكلمتان بنفس الصوت أم بصوت مختلف؟",
          "speak": "sun … moon",
          "options": [
            "✅ same",
            "❌ different"
          ],
          "correct": "❌ different"
        },
        {
          "promptEn": "🐷 pig — 🐼 panda: same first sound, or different?",
          "promptAr": "هل تبدأ الكلمتان بنفس الصوت أم بصوت مختلف؟",
          "speak": "pig … panda",
          "options": [
            "✅ same",
            "❌ different"
          ],
          "correct": "✅ same"
        },
        {
          "promptEn": "🐯 tiger — 🍎 apple: same first sound, or different?",
          "promptAr": "هل تبدأ الكلمتان بنفس الصوت أم بصوت مختلف؟",
          "speak": "tiger … apple",
          "options": [
            "✅ same",
            "❌ different"
          ],
          "correct": "❌ different"
        },
        {
          "promptEn": "🗺️ map — 🥛 milk: same first sound, or different?",
          "promptAr": "هل تبدأ الكلمتان بنفس الصوت أم بصوت مختلف؟",
          "speak": "map … milk",
          "options": [
            "✅ same",
            "❌ different"
          ],
          "correct": "✅ same"
        },
        {
          "promptEn": "🐜 ant — 🖊️ pen: same first sound, or different?",
          "promptAr": "هل تبدأ الكلمتان بنفس الصوت أم بصوت مختلف؟",
          "speak": "ant … pen",
          "options": [
            "✅ same",
            "❌ different"
          ],
          "correct": "❌ different"
        }
      ]
    },
    {
      "id": "challenge",
      "type": "mcq",
      "character": "malik",
      "audio": true,
      "tagEn": "Treasure Challenge",
      "tagAr": "تحدي الكنز",
      "instructionsEn": "Use all your sounds to open the treasure!",
      "instructionsAr": "استخدم كل الأصوات لتفتح الكنز!",
      "rounds": [
        {
          "promptEn": "Treasure clue: find the picture that starts with S!",
          "promptAr": "دليل الكنز: ابحث عن صورة تبدأ بالحرف S!",
          "speak": "S",
          "options": [
            "☀️ sun",
            "👩‍🚀 astronaut",
            "🐼 panda"
          ],
          "correct": "☀️ sun"
        },
        {
          "promptEn": "Treasure clue: find the picture that starts with A!",
          "promptAr": "دليل الكنز: ابحث عن صورة تبدأ بالحرف A!",
          "speak": "A",
          "options": [
            "🥛 milk",
            "🐜 ant",
            "🐼 panda"
          ],
          "correct": "🐜 ant"
        },
        {
          "promptEn": "Treasure clue: find the picture that starts with T!",
          "promptAr": "دليل الكنز: ابحث عن صورة تبدأ بالحرف T!",
          "speak": "T",
          "options": [
            "☀️ sun",
            "🐯 tiger",
            "🐷 pig"
          ],
          "correct": "🐯 tiger"
        },
        {
          "promptEn": "Treasure clue: find the picture that starts with P!",
          "promptAr": "دليل الكنز: ابحث عن صورة تبدأ بالحرف P!",
          "speak": "P",
          "options": [
            "🌙 moon",
            "🐷 pig",
            "☀️ sun"
          ],
          "correct": "🐷 pig"
        },
        {
          "promptEn": "Treasure clue: find the picture that starts with M!",
          "promptAr": "دليل الكنز: ابحث عن صورة تبدأ بالحرف M!",
          "speak": "M",
          "options": [
            "🚰 tap",
            "🌙 moon",
            "🍎 apple"
          ],
          "correct": "🌙 moon"
        }
      ]
    }
  ]
};

const ALL_GAMES = [GAME_SGATE, GAME_AGATE, GAME_TGATE, GAME_PGATE, GAME_MGATE, GAME_TREASURE];
